steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'cd hacku_kanazawa_2025_app && docker build -t gcr.io/$PROJECT_ID/next-app .'
      ]
images:
  - 'gcr.io/$PROJECT_ID/next-app'
