steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/next-app',
        '-f',
        'Dockerfile',
        '.'
      ]
    env:
      - 'AUTH_SECRET=${_AUTH_SECRET}'
      - 'AUTH_URL=${_AUTH_URL}'
      - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}'
      - 'GOOGLE_CLIENT_EMAIL=${_GOOGLE_CLIENT_EMAIL}'
      - 'GOOGLE_PRIVATE_KEY=${_GOOGLE_PRIVATE_KEY}'
      - 'GOOGLE_STOGAGE_BUCKET=${_GOOGLE_STOGAGE_BUCKET}'
      - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}'
      - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
images:
  - 'gcr.io/$PROJECT_ID/next-app'
