FROM node:18-alpine

# Build args
ARG AUTH_SECRET
ARG AUTH_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CLIENT_EMAIL
ARG GOOGLE_PRIVATE_KEY
ARG GOOGLE_STORAGE_BUCKET
ARG GOOGLE_APPLICATION_CREDENTIALS
ARG NEXTAUTH_SECRET
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Set env vars
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_URL=$AUTH_URL
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_CLIENT_EMAIL=$GOOGLE_CLIENT_EMAIL
ENV GOOGLE_PRIVATE_KEY="$GOOGLE_PRIVATE_KEY"
ENV GOOGLE_STORAGE_BUCKET=$GOOGLE_STORAGE_BUCKET
ENV GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

WORKDIR /app

# package.json と package-lock.json をコピー
COPY hacku_kanazawa_2025_app/package.json hacku_kanazawa_2025_app/package-lock.json ./

# npm ci でインストール（package-lock.json に従う）
RUN npm ci --only=production

# ソースコード全体をコピー
COPY hacku_kanazawa_2025_app ./

# Next.js アプリをビルド
RUN npm run build

EXPOSE 8080

# 本番モードで起動
CMD ["npm", "start"]
